/* 
 * Smarkets HTTP API
 *
 * This is the HTTP trading API for Smarkets. It can be used to trade on our exchange.     <br><br>For authenticated requests:<br>     <ul>     <li>Get a session token using the login route:     <a class=\"nostyle\" href=\"#/sessions/create_session\"><span>GET /v3/sessions/</span></a></li>     <li>Click on 'Authorize 🔓', enter your token after 'Session-Token ' and click on the 'Authorize' button</li>     </ul>     <p>In order to place bets and get the latest prices without restrictions     using this API, you need to be a Smarkets API user.<br></p>     <p>To become one, please fill <a href=\"https://docs.google.com/forms/d/1qI8RqypNimakPx- bmoUE_lA0YSP3YogKfL8N14STNSM/viewform?edit_requested=true\">this form</a>.</p>     <p>For questions and feedback about the API, use <a href=\"https://community.smarkets.com/c/developers\">our forum</a>.</p>     <p>The API is not public, but we are granting users access on an ongoing basis.</p>     <p>You can find some sample code to help you bootstrap your integration <a href=\"https://github.com/ smarkets/smk_trading_bot\">here</a>.</p>     
 *
 * OpenAPI spec version: 3
 * Contact: api@smarkets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LimitsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LimitsApiTests
    {
        private LimitsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LimitsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LimitsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LimitsApi
            //Assert.IsInstanceOfType(typeof(LimitsApi), instance, "instance is a LimitsApi");
        }

        /// <summary>
        /// Test AcknowledgeResponsibleGambling
        /// </summary>
        [Test]
        public void AcknowledgeResponsibleGamblingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AcknowledgeResponsibleGambling();
            //Assert.IsInstanceOf<ResponsibleGamblingAcknowledgeResponse> (response, "response is ResponsibleGamblingAcknowledgeResponse");
        }
        /// <summary>
        /// Test AcknowledgeSelfExclusionPromptSeen
        /// </summary>
        [Test]
        public void AcknowledgeSelfExclusionPromptSeenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AcknowledgeSelfExclusionPromptSeen();
            //Assert.IsInstanceOf<InlineResponse20035> (response, "response is InlineResponse20035");
        }
        /// <summary>
        /// Test DeleteLimits
        /// </summary>
        [Test]
        public void DeleteLimitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string limitType = null;
            //string status = null;
            //var response = instance.DeleteLimits(limitType, status);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test DeleteLimits_0
        /// </summary>
        [Test]
        public void DeleteLimits_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string limitType = null;
            //string interval = null;
            //string status = null;
            //var response = instance.DeleteLimits_0(limitType, interval, status);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test GetLimits
        /// </summary>
        [Test]
        public void GetLimitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string limitType = null;
            //var response = instance.GetLimits(limitType);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test GetResponsibleGamblingStatus
        /// </summary>
        [Test]
        public void GetResponsibleGamblingStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetResponsibleGamblingStatus();
            //Assert.IsInstanceOf<ResponsibleGamblingStatusResponse> (response, "response is ResponsibleGamblingStatusResponse");
        }
        /// <summary>
        /// Test GetSelfExclusionPromptSeen
        /// </summary>
        [Test]
        public void GetSelfExclusionPromptSeenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSelfExclusionPromptSeen();
            //Assert.IsInstanceOf<InlineResponse20035> (response, "response is InlineResponse20035");
        }
        /// <summary>
        /// Test PatchLimits
        /// </summary>
        [Test]
        public void PatchLimitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string limitType = null;
            //Body61 body = null;
            //var response = instance.PatchLimits(limitType, body);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test PatchLimits_0
        /// </summary>
        [Test]
        public void PatchLimits_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string limitType = null;
            //string interval = null;
            //Body62 body = null;
            //var response = instance.PatchLimits_0(limitType, interval, body);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test PostBreak
        /// </summary>
        [Test]
        public void PostBreakTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ModelBreak body = null;
            //var response = instance.PostBreak(body);
            //Assert.IsInstanceOf<BreakResponse> (response, "response is BreakResponse");
        }
        /// <summary>
        /// Test PostDepositLimits
        /// </summary>
        [Test]
        public void PostDepositLimitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body26 body = null;
            //var response = instance.PostDepositLimits(body);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test PostLossLimits
        /// </summary>
        [Test]
        public void PostLossLimitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body31 body = null;
            //var response = instance.PostLossLimits(body);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test PostSessionLimit
        /// </summary>
        [Test]
        public void PostSessionLimitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body51 body = null;
            //var response = instance.PostSessionLimit(body);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test PostStakeLimit
        /// </summary>
        [Test]
        public void PostStakeLimitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body54 body = null;
            //var response = instance.PostStakeLimit(body);
            //Assert.IsInstanceOf<LimitResponse> (response, "response is LimitResponse");
        }
        /// <summary>
        /// Test ProcessGamblingSelfTest
        /// </summary>
        [Test]
        public void ProcessGamblingSelfTestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GamblingSelfTestRequest body = null;
            //var response = instance.ProcessGamblingSelfTest(body);
            //Assert.IsInstanceOf<GamblingSelfTestResponse> (response, "response is GamblingSelfTestResponse");
        }
    }

}
