/* 
 * Smarkets HTTP API
 *
 * This is the HTTP trading API for Smarkets. It can be used to trade on our exchange.     <br><br>For authenticated requests:<br>     <ul>     <li>Get a session token using the login route:     <a class=\"nostyle\" href=\"#/sessions/create_session\"><span>GET /v3/sessions/</span></a></li>     <li>Click on 'Authorize 🔓', enter your token after 'Session-Token ' and click on the 'Authorize' button</li>     </ul>     <p>In order to place bets and get the latest prices without restrictions     using this API, you need to be a Smarkets API user.<br></p>     <p>To become one, please fill <a href=\"https://docs.google.com/forms/d/1qI8RqypNimakPx- bmoUE_lA0YSP3YogKfL8N14STNSM/viewform?edit_requested=true\">this form</a>.</p>     <p>For questions and feedback about the API, use <a href=\"https://community.smarkets.com/c/developers\">our forum</a>.</p>     <p>The API is not public, but we are granting users access on an ongoing basis.</p>     <p>You can find some sample code to help you bootstrap your integration <a href=\"https://github.com/ smarkets/smk_trading_bot\">here</a>.</p>     
 *
 * OpenAPI spec version: 3
 * Contact: api@smarkets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrdersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrdersApiTests
    {
        private OrdersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrdersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrdersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrdersApi
            //Assert.IsInstanceOfType(typeof(OrdersApi), instance, "instance is a OrdersApi");
        }

        /// <summary>
        /// Test CancelOrder
        /// </summary>
        [Test]
        public void CancelOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? orderId = null;
            //var response = instance.CancelOrder(orderId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test CancelOrders
        /// </summary>
        [Test]
        public void CancelOrdersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string marketId = null;
            //var response = instance.CancelOrders(marketId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test CreateAffiliateOrder
        /// </summary>
        [Test]
        public void CreateAffiliateOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body17 body = null;
            //var response = instance.CreateAffiliateOrder(body);
            //Assert.IsInstanceOf<InlineResponse20031> (response, "response is InlineResponse20031");
        }
        /// <summary>
        /// Test CreateOrder
        /// </summary>
        [Test]
        public void CreateOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body43 body = null;
            //var response = instance.CreateOrder(body);
            //Assert.IsInstanceOf<InlineResponse20053> (response, "response is InlineResponse20053");
        }
        /// <summary>
        /// Test GetOrderById
        /// </summary>
        [Test]
        public void GetOrderByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orderId = null;
            //var response = instance.GetOrderById(orderId);
            //Assert.IsInstanceOf<OrderResponse> (response, "response is OrderResponse");
        }
        /// <summary>
        /// Test GetOrders
        /// </summary>
        [Test]
        public void GetOrdersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contractId = null;
            //DateTime? createdDatetimeMax = null;
            //DateTime? createdDatetimeMin = null;
            //List<string> id = null;
            //int? limit = null;
            //List<string> marketId = null;
            //string paginationLastId = null;
            //int? sequenceNumberMax = null;
            //int? sequenceNumberMin = null;
            //List<string> state = null;
            //string side = null;
            //string sort = null;
            //var response = instance.GetOrders(contractId, createdDatetimeMax, createdDatetimeMin, id, limit, marketId, paginationLastId, sequenceNumberMax, sequenceNumberMin, state, side, sort);
            //Assert.IsInstanceOf<OrdersResponse> (response, "response is OrdersResponse");
        }
        /// <summary>
        /// Test GetOrdersV0
        /// </summary>
        [Test]
        public void GetOrdersV0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<int?> marketId = null;
            //List<int?> contractId = null;
            //string side = null;
            //List<string> state = null;
            //int? contractsLimit = null;
            //var response = instance.GetOrdersV0(marketId, contractId, side, state, contractsLimit);
            //Assert.IsInstanceOf<InlineResponse20011> (response, "response is InlineResponse20011");
        }
    }

}
