/* 
 * Smarkets HTTP API
 *
 * This is the HTTP trading API for Smarkets. It can be used to trade on our exchange.     <br><br>For authenticated requests:<br>     <ul>     <li>Get a session token using the login route:     <a class=\"nostyle\" href=\"#/sessions/create_session\"><span>GET /v3/sessions/</span></a></li>     <li>Click on 'Authorize 🔓', enter your token after 'Session-Token ' and click on the 'Authorize' button</li>     </ul>     <p>In order to place bets and get the latest prices without restrictions     using this API, you need to be a Smarkets API user.<br></p>     <p>To become one, please fill <a href=\"https://docs.google.com/forms/d/1qI8RqypNimakPx- bmoUE_lA0YSP3YogKfL8N14STNSM/viewform?edit_requested=true\">this form</a>.</p>     <p>For questions and feedback about the API, use <a href=\"https://community.smarkets.com/c/developers\">our forum</a>.</p>     <p>The API is not public, but we are granting users access on an ongoing basis.</p>     <p>You can find some sample code to help you bootstrap your integration <a href=\"https://github.com/ smarkets/smk_trading_bot\">here</a>.</p>     
 *
 * OpenAPI spec version: 3
 * Contact: api@smarkets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SettingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SettingsApiTests
    {
        private SettingsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SettingsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SettingsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SettingsApi
            //Assert.IsInstanceOfType(typeof(SettingsApi), instance, "instance is a SettingsApi");
        }

        /// <summary>
        /// Test ChangeEmailV0
        /// </summary>
        [Test]
        public void ChangeEmailV0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body7 body = null;
            //var response = instance.ChangeEmailV0(body);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test ChangePasswordV0
        /// </summary>
        [Test]
        public void ChangePasswordV0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body13 body = null;
            //var response = instance.ChangePasswordV0(body);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetConfig
        /// </summary>
        [Test]
        public void GetConfigTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetConfig();
            //Assert.IsInstanceOf<InlineResponse20019> (response, "response is InlineResponse20019");
        }
        /// <summary>
        /// Test GetLimitsV0
        /// </summary>
        [Test]
        public void GetLimitsV0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetLimitsV0();
            //Assert.IsInstanceOf<InlineResponse20022> (response, "response is InlineResponse20022");
        }
        /// <summary>
        /// Test GetPersonalV0
        /// </summary>
        [Test]
        public void GetPersonalV0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetPersonalV0();
            //Assert.IsInstanceOf<InlineResponse20027> (response, "response is InlineResponse20027");
        }
        /// <summary>
        /// Test InitialPersonalSettings
        /// </summary>
        [Test]
        public void InitialPersonalSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body15 body = null;
            //var response = instance.InitialPersonalSettings(body);
            //Assert.IsInstanceOf<Body15> (response, "response is Body15");
        }
        /// <summary>
        /// Test SelfExclude
        /// </summary>
        [Test]
        public void SelfExcludeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body8 body = null;
            //var response = instance.SelfExclude(body);
            //Assert.IsInstanceOf<InlineResponse20023> (response, "response is InlineResponse20023");
        }
        /// <summary>
        /// Test SetConfig
        /// </summary>
        [Test]
        public void SetConfigTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body6 body = null;
            //var response = instance.SetConfig(body);
            //Assert.IsInstanceOf<Body6> (response, "response is Body6");
        }
        /// <summary>
        /// Test SetPersonal
        /// </summary>
        [Test]
        public void SetPersonalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body14 body = null;
            //var response = instance.SetPersonal(body);
            //Assert.IsInstanceOf<Body14> (response, "response is Body14");
        }
        /// <summary>
        /// Test TimeOut
        /// </summary>
        [Test]
        public void TimeOutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body9 body = null;
            //var response = instance.TimeOut(body);
            //Assert.IsInstanceOf<InlineResponse20024> (response, "response is InlineResponse20024");
        }
    }

}
