/* 
 * Smarkets HTTP API
 *
 * This is the HTTP trading API for Smarkets. It can be used to trade on our exchange.     <br><br>For authenticated requests:<br>     <ul>     <li>Get a session token using the login route:     <a class=\"nostyle\" href=\"#/sessions/create_session\"><span>GET /v3/sessions/</span></a></li>     <li>Click on 'Authorize 🔓', enter your token after 'Session-Token ' and click on the 'Authorize' button</li>     </ul>     <p>In order to place bets and get the latest prices without restrictions     using this API, you need to be a Smarkets API user.<br></p>     <p>To become one, please fill <a href=\"https://docs.google.com/forms/d/1qI8RqypNimakPx- bmoUE_lA0YSP3YogKfL8N14STNSM/viewform?edit_requested=true\">this form</a>.</p>     <p>For questions and feedback about the API, use <a href=\"https://community.smarkets.com/c/developers\">our forum</a>.</p>     <p>The API is not public, but we are granting users access on an ongoing basis.</p>     <p>You can find some sample code to help you bootstrap your integration <a href=\"https://github.com/ smarkets/smk_trading_bot\">here</a>.</p>     
 *
 * OpenAPI spec version: 3
 * Contact: api@smarkets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body49
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body49Tests
    {
        // TODO uncomment below to declare an instance variable for Body49
        //private Body49 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body49
            //instance = new Body49();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body49
        /// </summary>
        [Test]
        public void Body49InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body49
            //Assert.IsInstanceOfType<Body49> (instance, "variable 'instance' is a Body49");
        }


        /// <summary>
        /// Test the property 'BuildingName'
        /// </summary>
        [Test]
        public void BuildingNameTest()
        {
            // TODO unit test for the property 'BuildingName'
        }
        /// <summary>
        /// Test the property 'BuildingNumber'
        /// </summary>
        [Test]
        public void BuildingNumberTest()
        {
            // TODO unit test for the property 'BuildingNumber'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'FlatNumber'
        /// </summary>
        [Test]
        public void FlatNumberTest()
        {
            // TODO unit test for the property 'FlatNumber'
        }
        /// <summary>
        /// Test the property 'NationalId'
        /// </summary>
        [Test]
        public void NationalIdTest()
        {
            // TODO unit test for the property 'NationalId'
        }
        /// <summary>
        /// Test the property 'Occupation'
        /// </summary>
        [Test]
        public void OccupationTest()
        {
            // TODO unit test for the property 'Occupation'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Test]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'Substreet'
        /// </summary>
        [Test]
        public void SubstreetTest()
        {
            // TODO unit test for the property 'Substreet'
        }
        /// <summary>
        /// Test the property 'Town'
        /// </summary>
        [Test]
        public void TownTest()
        {
            // TODO unit test for the property 'Town'
        }

    }

}
