/* 
 * Smarkets HTTP API
 *
 * This is the HTTP trading API for Smarkets. It can be used to trade on our exchange.     <br><br>For authenticated requests:<br>     <ul>     <li>Get a session token using the login route:     <a class=\"nostyle\" href=\"#/sessions/create_session\"><span>GET /v3/sessions/</span></a></li>     <li>Click on 'Authorize 🔓', enter your token after 'Session-Token ' and click on the 'Authorize' button</li>     </ul>     <p>In order to place bets and get the latest prices without restrictions     using this API, you need to be a Smarkets API user.<br></p>     <p>To become one, please fill <a href=\"https://docs.google.com/forms/d/1qI8RqypNimakPx- bmoUE_lA0YSP3YogKfL8N14STNSM/viewform?edit_requested=true\">this form</a>.</p>     <p>For questions and feedback about the API, use <a href=\"https://community.smarkets.com/c/developers\">our forum</a>.</p>     <p>The API is not public, but we are granting users access on an ongoing basis.</p>     <p>You can find some sample code to help you bootstrap your integration <a href=\"https://github.com/ smarkets/smk_trading_bot\">here</a>.</p>     
 *
 * OpenAPI spec version: 3
 * Contact: api@smarkets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DepositMethodsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DepositMethodsResponseTests
    {
        // TODO uncomment below to declare an instance variable for DepositMethodsResponse
        //private DepositMethodsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DepositMethodsResponse
            //instance = new DepositMethodsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DepositMethodsResponse
        /// </summary>
        [Test]
        public void DepositMethodsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DepositMethodsResponse
            //Assert.IsInstanceOfType<DepositMethodsResponse> (instance, "variable 'instance' is a DepositMethodsResponse");
        }


        /// <summary>
        /// Test the property 'BankTransfer'
        /// </summary>
        [Test]
        public void BankTransferTest()
        {
            // TODO unit test for the property 'BankTransfer'
        }
        /// <summary>
        /// Test the property 'Card'
        /// </summary>
        [Test]
        public void CardTest()
        {
            // TODO unit test for the property 'Card'
        }
        /// <summary>
        /// Test the property 'Neteller'
        /// </summary>
        [Test]
        public void NetellerTest()
        {
            // TODO unit test for the property 'Neteller'
        }
        /// <summary>
        /// Test the property 'OpenBankTransfer'
        /// </summary>
        [Test]
        public void OpenBankTransferTest()
        {
            // TODO unit test for the property 'OpenBankTransfer'
        }
        /// <summary>
        /// Test the property 'Paypal'
        /// </summary>
        [Test]
        public void PaypalTest()
        {
            // TODO unit test for the property 'Paypal'
        }
        /// <summary>
        /// Test the property 'Skrill'
        /// </summary>
        [Test]
        public void SkrillTest()
        {
            // TODO unit test for the property 'Skrill'
        }
        /// <summary>
        /// Test the property 'Trustly'
        /// </summary>
        [Test]
        public void TrustlyTest()
        {
            // TODO unit test for the property 'Trustly'
        }
        /// <summary>
        /// Test the property 'Worldpay'
        /// </summary>
        [Test]
        public void WorldpayTest()
        {
            // TODO unit test for the property 'Worldpay'
        }

    }

}
