/* 
 * Smarkets HTTP API
 *
 * This is the HTTP trading API for Smarkets. It can be used to trade on our exchange.     <br><br>For authenticated requests:<br>     <ul>     <li>Get a session token using the login route:     <a class=\"nostyle\" href=\"#/sessions/create_session\"><span>GET /v3/sessions/</span></a></li>     <li>Click on 'Authorize 🔓', enter your token after 'Session-Token ' and click on the 'Authorize' button</li>     </ul>     <p>In order to place bets and get the latest prices without restrictions     using this API, you need to be a Smarkets API user.<br></p>     <p>To become one, please fill <a href=\"https://docs.google.com/forms/d/1qI8RqypNimakPx- bmoUE_lA0YSP3YogKfL8N14STNSM/viewform?edit_requested=true\">this form</a>.</p>     <p>For questions and feedback about the API, use <a href=\"https://community.smarkets.com/c/developers\">our forum</a>.</p>     <p>The API is not public, but we are granting users access on an ongoing basis.</p>     <p>You can find some sample code to help you bootstrap your integration <a href=\"https://github.com/ smarkets/smk_trading_bot\">here</a>.</p>     
 *
 * OpenAPI spec version: 3
 * Contact: api@smarkets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelEventTests
    {
        // TODO uncomment below to declare an instance variable for ModelEvent
        //private ModelEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelEvent
            //instance = new ModelEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelEvent
        /// </summary>
        [Test]
        public void ModelEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelEvent
            //Assert.IsInstanceOfType<ModelEvent> (instance, "variable 'instance' is a ModelEvent");
        }


        /// <summary>
        /// Test the property 'BetAllowed'
        /// </summary>
        [Test]
        public void BetAllowedTest()
        {
            // TODO unit test for the property 'BetAllowed'
        }
        /// <summary>
        /// Test the property 'Bettable'
        /// </summary>
        [Test]
        public void BettableTest()
        {
            // TODO unit test for the property 'Bettable'
        }
        /// <summary>
        /// Test the property 'ChartTimePeriod'
        /// </summary>
        [Test]
        public void ChartTimePeriodTest()
        {
            // TODO unit test for the property 'ChartTimePeriod'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DisplayOrder'
        /// </summary>
        [Test]
        public void DisplayOrderTest()
        {
            // TODO unit test for the property 'DisplayOrder'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'FullSlug'
        /// </summary>
        [Test]
        public void FullSlugTest()
        {
            // TODO unit test for the property 'FullSlug'
        }
        /// <summary>
        /// Test the property 'Hidden'
        /// </summary>
        [Test]
        public void HiddenTest()
        {
            // TODO unit test for the property 'Hidden'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'InplayEnabled'
        /// </summary>
        [Test]
        public void InplayEnabledTest()
        {
            // TODO unit test for the property 'InplayEnabled'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Test]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'SeoDescription'
        /// </summary>
        [Test]
        public void SeoDescriptionTest()
        {
            // TODO unit test for the property 'SeoDescription'
        }
        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Test]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }
        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Test]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }
        /// <summary>
        /// Test the property 'SpecialRules'
        /// </summary>
        [Test]
        public void SpecialRulesTest()
        {
            // TODO unit test for the property 'SpecialRules'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'StartDatetime'
        /// </summary>
        [Test]
        public void StartDatetimeTest()
        {
            // TODO unit test for the property 'StartDatetime'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
