/* 
 * Smarkets HTTP API
 *
 * This is the HTTP trading API for Smarkets. It can be used to trade on our exchange.     <br><br>For authenticated requests:<br>     <ul>     <li>Get a session token using the login route:     <a class=\"nostyle\" href=\"#/sessions/create_session\"><span>GET /v3/sessions/</span></a></li>     <li>Click on 'Authorize 🔓', enter your token after 'Session-Token ' and click on the 'Authorize' button</li>     </ul>     <p>In order to place bets and get the latest prices without restrictions     using this API, you need to be a Smarkets API user.<br></p>     <p>To become one, please fill <a href=\"https://docs.google.com/forms/d/1qI8RqypNimakPx- bmoUE_lA0YSP3YogKfL8N14STNSM/viewform?edit_requested=true\">this form</a>.</p>     <p>For questions and feedback about the API, use <a href=\"https://community.smarkets.com/c/developers\">our forum</a>.</p>     <p>The API is not public, but we are granting users access on an ongoing basis.</p>     <p>You can find some sample code to help you bootstrap your integration <a href=\"https://github.com/ smarkets/smk_trading_bot\">here</a>.</p>     
 *
 * OpenAPI spec version: 3
 * Contact: api@smarkets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Body50
    /// </summary>
    [DataContract]
        public partial class Body50 :  IEquatable<Body50>, IValidatableObject
    {
        /// <summary>
        /// Defines CardSize
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum CardSizeEnum
        {
            /// <summary>
            /// Enum Large for value: large
            /// </summary>
            [EnumMember(Value = "large")]
            Large = 1,
            /// <summary>
            /// Enum Small for value: small
            /// </summary>
            [EnumMember(Value = "small")]
            Small = 2        }
        /// <summary>
        /// Gets or Sets CardSize
        /// </summary>
        [DataMember(Name="card_size", EmitDefaultValue=false)]
        public CardSizeEnum? CardSize { get; set; }
        /// <summary>
        /// Defines ColourTheme
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ColourThemeEnum
        {
            /// <summary>
            /// Enum Light for value: light
            /// </summary>
            [EnumMember(Value = "light")]
            Light = 1,
            /// <summary>
            /// Enum Dark for value: dark
            /// </summary>
            [EnumMember(Value = "dark")]
            Dark = 2,
            /// <summary>
            /// Enum Null for value: null
            /// </summary>
            [EnumMember(Value = null)]
            Null = 3        }
        /// <summary>
        /// Gets or Sets ColourTheme
        /// </summary>
        [DataMember(Name="colour_theme", EmitDefaultValue=false)]
        public ColourThemeEnum? ColourTheme { get; set; }
        /// <summary>
        /// Defines GraphsMinimizeByDefault
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum GraphsMinimizeByDefaultEnum
        {
            /// <summary>
            /// Enum Auto for value: auto
            /// </summary>
            [EnumMember(Value = "auto")]
            Auto = 1,
            /// <summary>
            /// Enum Always for value: always
            /// </summary>
            [EnumMember(Value = "always")]
            Always = 2,
            /// <summary>
            /// Enum Never for value: never
            /// </summary>
            [EnumMember(Value = "never")]
            Never = 3        }
        /// <summary>
        /// Gets or Sets GraphsMinimizeByDefault
        /// </summary>
        [DataMember(Name="graphs_minimize_by_default", EmitDefaultValue=false)]
        public GraphsMinimizeByDefaultEnum? GraphsMinimizeByDefault { get; set; }
        /// <summary>
        /// Defines KeyboardEntryFormat
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum KeyboardEntryFormatEnum
        {
            /// <summary>
            /// Enum Number for value: number
            /// </summary>
            [EnumMember(Value = "number")]
            Number = 1,
            /// <summary>
            /// Enum Percentage for value: percentage
            /// </summary>
            [EnumMember(Value = "percentage")]
            Percentage = 2        }
        /// <summary>
        /// Gets or Sets KeyboardEntryFormat
        /// </summary>
        [DataMember(Name="keyboard_entry_format", EmitDefaultValue=false)]
        public KeyboardEntryFormatEnum? KeyboardEntryFormat { get; set; }
        /// <summary>
        /// Defines KeyboardInputMethod
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum KeyboardInputMethodEnum
        {
            /// <summary>
            /// Enum Additive for value: additive
            /// </summary>
            [EnumMember(Value = "additive")]
            Additive = 1,
            /// <summary>
            /// Enum Replace for value: replace
            /// </summary>
            [EnumMember(Value = "replace")]
            Replace = 2        }
        /// <summary>
        /// Gets or Sets KeyboardInputMethod
        /// </summary>
        [DataMember(Name="keyboard_input_method", EmitDefaultValue=false)]
        public KeyboardInputMethodEnum? KeyboardInputMethod { get; set; }
        /// <summary>
        /// Defines Locale
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum LocaleEnum
        {
            /// <summary>
            /// Enum El for value: el
            /// </summary>
            [EnumMember(Value = "el")]
            El = 1,
            /// <summary>
            /// Enum Ro for value: ro
            /// </summary>
            [EnumMember(Value = "ro")]
            Ro = 2,
            /// <summary>
            /// Enum Sv for value: sv
            /// </summary>
            [EnumMember(Value = "sv")]
            Sv = 3,
            /// <summary>
            /// Enum It for value: it
            /// </summary>
            [EnumMember(Value = "it")]
            It = 4,
            /// <summary>
            /// Enum Pl for value: pl
            /// </summary>
            [EnumMember(Value = "pl")]
            Pl = 5,
            /// <summary>
            /// Enum Es for value: es
            /// </summary>
            [EnumMember(Value = "es")]
            Es = 6,
            /// <summary>
            /// Enum En for value: en
            /// </summary>
            [EnumMember(Value = "en")]
            En = 7,
            /// <summary>
            /// Enum Ru for value: ru
            /// </summary>
            [EnumMember(Value = "ru")]
            Ru = 8,
            /// <summary>
            /// Enum Fi for value: fi
            /// </summary>
            [EnumMember(Value = "fi")]
            Fi = 9,
            /// <summary>
            /// Enum Da for value: da
            /// </summary>
            [EnumMember(Value = "da")]
            Da = 10,
            /// <summary>
            /// Enum Fr for value: fr
            /// </summary>
            [EnumMember(Value = "fr")]
            Fr = 11,
            /// <summary>
            /// Enum PtPT for value: pt-PT
            /// </summary>
            [EnumMember(Value = "pt-PT")]
            PtPT = 12,
            /// <summary>
            /// Enum ZhHant for value: zh-Hant
            /// </summary>
            [EnumMember(Value = "zh-Hant")]
            ZhHant = 13,
            /// <summary>
            /// Enum Lt for value: lt
            /// </summary>
            [EnumMember(Value = "lt")]
            Lt = 14,
            /// <summary>
            /// Enum De for value: de
            /// </summary>
            [EnumMember(Value = "de")]
            De = 15,
            /// <summary>
            /// Enum Hr for value: hr
            /// </summary>
            [EnumMember(Value = "hr")]
            Hr = 16,
            /// <summary>
            /// Enum ZhHans for value: zh-Hans
            /// </summary>
            [EnumMember(Value = "zh-Hans")]
            ZhHans = 17,
            /// <summary>
            /// Enum EnUS for value: en-US
            /// </summary>
            [EnumMember(Value = "en-US")]
            EnUS = 18,
            /// <summary>
            /// Enum Null for value: null
            /// </summary>
            [EnumMember(Value = null)]
            Null = 19        }
        /// <summary>
        /// Gets or Sets Locale
        /// </summary>
        [DataMember(Name="locale", EmitDefaultValue=false)]
        public LocaleEnum? Locale { get; set; }
        /// <summary>
        /// Defines OddsFormat
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum OddsFormatEnum
        {
            /// <summary>
            /// Enum Decimal for value: decimal
            /// </summary>
            [EnumMember(Value = "decimal")]
            Decimal = 1,
            /// <summary>
            /// Enum American for value: american
            /// </summary>
            [EnumMember(Value = "american")]
            American = 2,
            /// <summary>
            /// Enum Fractional for value: fractional
            /// </summary>
            [EnumMember(Value = "fractional")]
            Fractional = 3,
            /// <summary>
            /// Enum Percent for value: percent
            /// </summary>
            [EnumMember(Value = "percent")]
            Percent = 4        }
        /// <summary>
        /// Gets or Sets OddsFormat
        /// </summary>
        [DataMember(Name="odds_format", EmitDefaultValue=false)]
        public OddsFormatEnum? OddsFormat { get; set; }
        /// <summary>
        /// Defines SettlementNotification
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum SettlementNotificationEnum
        {
            /// <summary>
            /// Enum Contractgroupsettlement for value: contract_group_settlement
            /// </summary>
            [EnumMember(Value = "contract_group_settlement")]
            Contractgroupsettlement = 1,
            /// <summary>
            /// Enum Dailysettlementdigest for value: daily_settlement_digest
            /// </summary>
            [EnumMember(Value = "daily_settlement_digest")]
            Dailysettlementdigest = 2,
            /// <summary>
            /// Enum Nonotification for value: no_notification
            /// </summary>
            [EnumMember(Value = "no_notification")]
            Nonotification = 3        }
        /// <summary>
        /// Gets or Sets SettlementNotification
        /// </summary>
        [DataMember(Name="settlement_notification", EmitDefaultValue=false)]
        public SettlementNotificationEnum? SettlementNotification { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Body50" /> class.
        /// </summary>
        /// <param name="cardSize">cardSize.</param>
        /// <param name="colourBlind">colourBlind.</param>
        /// <param name="colourTheme">colourTheme.</param>
        /// <param name="graphsMinimizeByDefault">graphsMinimizeByDefault.</param>
        /// <param name="graphsUseMemberOddsFormat">graphsUseMemberOddsFormat.</param>
        /// <param name="hideBalance">hideBalance.</param>
        /// <param name="instantBet">instantBet.</param>
        /// <param name="keyboardConfigPreviouslySet">keyboardConfigPreviouslySet.</param>
        /// <param name="keyboardEntryFormat">keyboardEntryFormat.</param>
        /// <param name="keyboardInputMethod">keyboardInputMethod.</param>
        /// <param name="keyboardKeys">keyboardKeys.</param>
        /// <param name="locale">locale.</param>
        /// <param name="mailingList">mailingList.</param>
        /// <param name="oddsFormat">oddsFormat.</param>
        /// <param name="settlementNotification">settlementNotification.</param>
        /// <param name="showBackerStake">showBackerStake.</param>
        public Body50(CardSizeEnum? cardSize = default(CardSizeEnum?), bool? colourBlind = default(bool?), ColourThemeEnum? colourTheme = default(ColourThemeEnum?), GraphsMinimizeByDefaultEnum? graphsMinimizeByDefault = default(GraphsMinimizeByDefaultEnum?), bool? graphsUseMemberOddsFormat = default(bool?), bool? hideBalance = default(bool?), bool? instantBet = default(bool?), bool? keyboardConfigPreviouslySet = default(bool?), KeyboardEntryFormatEnum? keyboardEntryFormat = default(KeyboardEntryFormatEnum?), KeyboardInputMethodEnum? keyboardInputMethod = default(KeyboardInputMethodEnum?), List<string> keyboardKeys = default(List<string>), LocaleEnum? locale = default(LocaleEnum?), bool? mailingList = default(bool?), OddsFormatEnum? oddsFormat = default(OddsFormatEnum?), SettlementNotificationEnum? settlementNotification = default(SettlementNotificationEnum?), bool? showBackerStake = default(bool?))
        {
            this.CardSize = cardSize;
            this.ColourBlind = colourBlind;
            this.ColourTheme = colourTheme;
            this.GraphsMinimizeByDefault = graphsMinimizeByDefault;
            this.GraphsUseMemberOddsFormat = graphsUseMemberOddsFormat;
            this.HideBalance = hideBalance;
            this.InstantBet = instantBet;
            this.KeyboardConfigPreviouslySet = keyboardConfigPreviouslySet;
            this.KeyboardEntryFormat = keyboardEntryFormat;
            this.KeyboardInputMethod = keyboardInputMethod;
            this.KeyboardKeys = keyboardKeys;
            this.Locale = locale;
            this.MailingList = mailingList;
            this.OddsFormat = oddsFormat;
            this.SettlementNotification = settlementNotification;
            this.ShowBackerStake = showBackerStake;
        }
        

        /// <summary>
        /// Gets or Sets ColourBlind
        /// </summary>
        [DataMember(Name="colour_blind", EmitDefaultValue=false)]
        public bool? ColourBlind { get; set; }



        /// <summary>
        /// Gets or Sets GraphsUseMemberOddsFormat
        /// </summary>
        [DataMember(Name="graphs_use_member_odds_format", EmitDefaultValue=false)]
        public bool? GraphsUseMemberOddsFormat { get; set; }

        /// <summary>
        /// Gets or Sets HideBalance
        /// </summary>
        [DataMember(Name="hide_balance", EmitDefaultValue=false)]
        public bool? HideBalance { get; set; }

        /// <summary>
        /// Gets or Sets InstantBet
        /// </summary>
        [DataMember(Name="instant_bet", EmitDefaultValue=false)]
        public bool? InstantBet { get; set; }

        /// <summary>
        /// Gets or Sets KeyboardConfigPreviouslySet
        /// </summary>
        [DataMember(Name="keyboard_config_previously_set", EmitDefaultValue=false)]
        public bool? KeyboardConfigPreviouslySet { get; set; }



        /// <summary>
        /// Gets or Sets KeyboardKeys
        /// </summary>
        [DataMember(Name="keyboard_keys", EmitDefaultValue=false)]
        public List<string> KeyboardKeys { get; set; }


        /// <summary>
        /// Gets or Sets MailingList
        /// </summary>
        [DataMember(Name="mailing_list", EmitDefaultValue=false)]
        public bool? MailingList { get; set; }



        /// <summary>
        /// Gets or Sets ShowBackerStake
        /// </summary>
        [DataMember(Name="show_backer_stake", EmitDefaultValue=false)]
        public bool? ShowBackerStake { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Body50 {\n");
            sb.Append("  CardSize: ").Append(CardSize).Append("\n");
            sb.Append("  ColourBlind: ").Append(ColourBlind).Append("\n");
            sb.Append("  ColourTheme: ").Append(ColourTheme).Append("\n");
            sb.Append("  GraphsMinimizeByDefault: ").Append(GraphsMinimizeByDefault).Append("\n");
            sb.Append("  GraphsUseMemberOddsFormat: ").Append(GraphsUseMemberOddsFormat).Append("\n");
            sb.Append("  HideBalance: ").Append(HideBalance).Append("\n");
            sb.Append("  InstantBet: ").Append(InstantBet).Append("\n");
            sb.Append("  KeyboardConfigPreviouslySet: ").Append(KeyboardConfigPreviouslySet).Append("\n");
            sb.Append("  KeyboardEntryFormat: ").Append(KeyboardEntryFormat).Append("\n");
            sb.Append("  KeyboardInputMethod: ").Append(KeyboardInputMethod).Append("\n");
            sb.Append("  KeyboardKeys: ").Append(KeyboardKeys).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  MailingList: ").Append(MailingList).Append("\n");
            sb.Append("  OddsFormat: ").Append(OddsFormat).Append("\n");
            sb.Append("  SettlementNotification: ").Append(SettlementNotification).Append("\n");
            sb.Append("  ShowBackerStake: ").Append(ShowBackerStake).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Body50);
        }

        /// <summary>
        /// Returns true if Body50 instances are equal
        /// </summary>
        /// <param name="input">Instance of Body50 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Body50 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CardSize == input.CardSize ||
                    (this.CardSize != null &&
                    this.CardSize.Equals(input.CardSize))
                ) && 
                (
                    this.ColourBlind == input.ColourBlind ||
                    (this.ColourBlind != null &&
                    this.ColourBlind.Equals(input.ColourBlind))
                ) && 
                (
                    this.ColourTheme == input.ColourTheme ||
                    (this.ColourTheme != null &&
                    this.ColourTheme.Equals(input.ColourTheme))
                ) && 
                (
                    this.GraphsMinimizeByDefault == input.GraphsMinimizeByDefault ||
                    (this.GraphsMinimizeByDefault != null &&
                    this.GraphsMinimizeByDefault.Equals(input.GraphsMinimizeByDefault))
                ) && 
                (
                    this.GraphsUseMemberOddsFormat == input.GraphsUseMemberOddsFormat ||
                    (this.GraphsUseMemberOddsFormat != null &&
                    this.GraphsUseMemberOddsFormat.Equals(input.GraphsUseMemberOddsFormat))
                ) && 
                (
                    this.HideBalance == input.HideBalance ||
                    (this.HideBalance != null &&
                    this.HideBalance.Equals(input.HideBalance))
                ) && 
                (
                    this.InstantBet == input.InstantBet ||
                    (this.InstantBet != null &&
                    this.InstantBet.Equals(input.InstantBet))
                ) && 
                (
                    this.KeyboardConfigPreviouslySet == input.KeyboardConfigPreviouslySet ||
                    (this.KeyboardConfigPreviouslySet != null &&
                    this.KeyboardConfigPreviouslySet.Equals(input.KeyboardConfigPreviouslySet))
                ) && 
                (
                    this.KeyboardEntryFormat == input.KeyboardEntryFormat ||
                    (this.KeyboardEntryFormat != null &&
                    this.KeyboardEntryFormat.Equals(input.KeyboardEntryFormat))
                ) && 
                (
                    this.KeyboardInputMethod == input.KeyboardInputMethod ||
                    (this.KeyboardInputMethod != null &&
                    this.KeyboardInputMethod.Equals(input.KeyboardInputMethod))
                ) && 
                (
                    this.KeyboardKeys == input.KeyboardKeys ||
                    this.KeyboardKeys != null &&
                    input.KeyboardKeys != null &&
                    this.KeyboardKeys.SequenceEqual(input.KeyboardKeys)
                ) && 
                (
                    this.Locale == input.Locale ||
                    (this.Locale != null &&
                    this.Locale.Equals(input.Locale))
                ) && 
                (
                    this.MailingList == input.MailingList ||
                    (this.MailingList != null &&
                    this.MailingList.Equals(input.MailingList))
                ) && 
                (
                    this.OddsFormat == input.OddsFormat ||
                    (this.OddsFormat != null &&
                    this.OddsFormat.Equals(input.OddsFormat))
                ) && 
                (
                    this.SettlementNotification == input.SettlementNotification ||
                    (this.SettlementNotification != null &&
                    this.SettlementNotification.Equals(input.SettlementNotification))
                ) && 
                (
                    this.ShowBackerStake == input.ShowBackerStake ||
                    (this.ShowBackerStake != null &&
                    this.ShowBackerStake.Equals(input.ShowBackerStake))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CardSize != null)
                    hashCode = hashCode * 59 + this.CardSize.GetHashCode();
                if (this.ColourBlind != null)
                    hashCode = hashCode * 59 + this.ColourBlind.GetHashCode();
                if (this.ColourTheme != null)
                    hashCode = hashCode * 59 + this.ColourTheme.GetHashCode();
                if (this.GraphsMinimizeByDefault != null)
                    hashCode = hashCode * 59 + this.GraphsMinimizeByDefault.GetHashCode();
                if (this.GraphsUseMemberOddsFormat != null)
                    hashCode = hashCode * 59 + this.GraphsUseMemberOddsFormat.GetHashCode();
                if (this.HideBalance != null)
                    hashCode = hashCode * 59 + this.HideBalance.GetHashCode();
                if (this.InstantBet != null)
                    hashCode = hashCode * 59 + this.InstantBet.GetHashCode();
                if (this.KeyboardConfigPreviouslySet != null)
                    hashCode = hashCode * 59 + this.KeyboardConfigPreviouslySet.GetHashCode();
                if (this.KeyboardEntryFormat != null)
                    hashCode = hashCode * 59 + this.KeyboardEntryFormat.GetHashCode();
                if (this.KeyboardInputMethod != null)
                    hashCode = hashCode * 59 + this.KeyboardInputMethod.GetHashCode();
                if (this.KeyboardKeys != null)
                    hashCode = hashCode * 59 + this.KeyboardKeys.GetHashCode();
                if (this.Locale != null)
                    hashCode = hashCode * 59 + this.Locale.GetHashCode();
                if (this.MailingList != null)
                    hashCode = hashCode * 59 + this.MailingList.GetHashCode();
                if (this.OddsFormat != null)
                    hashCode = hashCode * 59 + this.OddsFormat.GetHashCode();
                if (this.SettlementNotification != null)
                    hashCode = hashCode * 59 + this.SettlementNotification.GetHashCode();
                if (this.ShowBackerStake != null)
                    hashCode = hashCode * 59 + this.ShowBackerStake.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
