/* 
 * Smarkets HTTP API
 *
 * This is the HTTP trading API for Smarkets. It can be used to trade on our exchange.     <br><br>For authenticated requests:<br>     <ul>     <li>Get a session token using the login route:     <a class=\"nostyle\" href=\"#/sessions/create_session\"><span>GET /v3/sessions/</span></a></li>     <li>Click on 'Authorize 🔓', enter your token after 'Session-Token ' and click on the 'Authorize' button</li>     </ul>     <p>In order to place bets and get the latest prices without restrictions     using this API, you need to be a Smarkets API user.<br></p>     <p>To become one, please fill <a href=\"https://docs.google.com/forms/d/1qI8RqypNimakPx- bmoUE_lA0YSP3YogKfL8N14STNSM/viewform?edit_requested=true\">this form</a>.</p>     <p>For questions and feedback about the API, use <a href=\"https://community.smarkets.com/c/developers\">our forum</a>.</p>     <p>The API is not public, but we are granting users access on an ongoing basis.</p>     <p>You can find some sample code to help you bootstrap your integration <a href=\"https://github.com/ smarkets/smk_trading_bot\">here</a>.</p>     
 *
 * OpenAPI spec version: 3
 * Contact: api@smarkets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// GetCommentsReponseComments
    /// </summary>
    [DataContract]
        public partial class GetCommentsReponseComments :  IEquatable<GetCommentsReponseComments>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCommentsReponseComments" /> class.
        /// </summary>
        /// <param name="commentText">commentText (required).</param>
        /// <param name="contractId">This ID uniquely identifies the contract (required).</param>
        /// <param name="created">created (required).</param>
        /// <param name="eventId">This ID uniquely identifies an event (required).</param>
        /// <param name="hideStake">hideStake (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="legacyCommentId">legacyCommentId.</param>
        /// <param name="link">link (required).</param>
        /// <param name="marketId">This ID uniquely identifies the market (required).</param>
        /// <param name="memberId">memberId (required).</param>
        /// <param name="mentions">mentions (required).</param>
        /// <param name="numComments">numComments (required).</param>
        /// <param name="odds">odds (required).</param>
        /// <param name="parentCommentId">parentCommentId (required).</param>
        /// <param name="reactions">reactions (required).</param>
        /// <param name="stake">stake (required).</param>
        public GetCommentsReponseComments(string commentText = default(string), string contractId = default(string), string created = default(string), string eventId = default(string), bool? hideStake = default(bool?), int? id = default(int?), int? legacyCommentId = default(int?), string link = default(string), string marketId = default(string), int? memberId = default(int?), List<int?> mentions = default(List<int?>), int? numComments = default(int?), int? odds = default(int?), int? parentCommentId = default(int?), Object reactions = default(Object), string stake = default(string))
        {
            // to ensure "commentText" is required (not null)
            if (commentText == null)
            {
                throw new InvalidDataException("commentText is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.CommentText = commentText;
            }
            // to ensure "contractId" is required (not null)
            if (contractId == null)
            {
                throw new InvalidDataException("contractId is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.ContractId = contractId;
            }
            // to ensure "created" is required (not null)
            if (created == null)
            {
                throw new InvalidDataException("created is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.Created = created;
            }
            // to ensure "eventId" is required (not null)
            if (eventId == null)
            {
                throw new InvalidDataException("eventId is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.EventId = eventId;
            }
            // to ensure "hideStake" is required (not null)
            if (hideStake == null)
            {
                throw new InvalidDataException("hideStake is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.HideStake = hideStake;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "link" is required (not null)
            if (link == null)
            {
                throw new InvalidDataException("link is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.Link = link;
            }
            // to ensure "marketId" is required (not null)
            if (marketId == null)
            {
                throw new InvalidDataException("marketId is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.MarketId = marketId;
            }
            // to ensure "memberId" is required (not null)
            if (memberId == null)
            {
                throw new InvalidDataException("memberId is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.MemberId = memberId;
            }
            // to ensure "mentions" is required (not null)
            if (mentions == null)
            {
                throw new InvalidDataException("mentions is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.Mentions = mentions;
            }
            // to ensure "numComments" is required (not null)
            if (numComments == null)
            {
                throw new InvalidDataException("numComments is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.NumComments = numComments;
            }
            // to ensure "odds" is required (not null)
            if (odds == null)
            {
                throw new InvalidDataException("odds is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.Odds = odds;
            }
            // to ensure "parentCommentId" is required (not null)
            if (parentCommentId == null)
            {
                throw new InvalidDataException("parentCommentId is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.ParentCommentId = parentCommentId;
            }
            // to ensure "reactions" is required (not null)
            if (reactions == null)
            {
                throw new InvalidDataException("reactions is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.Reactions = reactions;
            }
            // to ensure "stake" is required (not null)
            if (stake == null)
            {
                throw new InvalidDataException("stake is a required property for GetCommentsReponseComments and cannot be null");
            }
            else
            {
                this.Stake = stake;
            }
            this.LegacyCommentId = legacyCommentId;
        }
        
        /// <summary>
        /// Gets or Sets CommentText
        /// </summary>
        [DataMember(Name="comment_text", EmitDefaultValue=false)]
        public string CommentText { get; set; }

        /// <summary>
        /// This ID uniquely identifies the contract
        /// </summary>
        /// <value>This ID uniquely identifies the contract</value>
        [DataMember(Name="contract_id", EmitDefaultValue=false)]
        public string ContractId { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name="created", EmitDefaultValue=false)]
        public string Created { get; set; }

        /// <summary>
        /// This ID uniquely identifies an event
        /// </summary>
        /// <value>This ID uniquely identifies an event</value>
        [DataMember(Name="event_id", EmitDefaultValue=false)]
        public string EventId { get; set; }

        /// <summary>
        /// Gets or Sets HideStake
        /// </summary>
        [DataMember(Name="hide_stake", EmitDefaultValue=false)]
        public bool? HideStake { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets LegacyCommentId
        /// </summary>
        [DataMember(Name="legacy_comment_id", EmitDefaultValue=false)]
        public int? LegacyCommentId { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name="link", EmitDefaultValue=false)]
        public string Link { get; set; }

        /// <summary>
        /// This ID uniquely identifies the market
        /// </summary>
        /// <value>This ID uniquely identifies the market</value>
        [DataMember(Name="market_id", EmitDefaultValue=false)]
        public string MarketId { get; set; }

        /// <summary>
        /// Gets or Sets MemberId
        /// </summary>
        [DataMember(Name="member_id", EmitDefaultValue=false)]
        public int? MemberId { get; set; }

        /// <summary>
        /// Gets or Sets Mentions
        /// </summary>
        [DataMember(Name="mentions", EmitDefaultValue=false)]
        public List<int?> Mentions { get; set; }

        /// <summary>
        /// Gets or Sets NumComments
        /// </summary>
        [DataMember(Name="num_comments", EmitDefaultValue=false)]
        public int? NumComments { get; set; }

        /// <summary>
        /// Gets or Sets Odds
        /// </summary>
        [DataMember(Name="odds", EmitDefaultValue=false)]
        public int? Odds { get; set; }

        /// <summary>
        /// Gets or Sets ParentCommentId
        /// </summary>
        [DataMember(Name="parent_comment_id", EmitDefaultValue=false)]
        public int? ParentCommentId { get; set; }

        /// <summary>
        /// Gets or Sets Reactions
        /// </summary>
        [DataMember(Name="reactions", EmitDefaultValue=false)]
        public Object Reactions { get; set; }

        /// <summary>
        /// Gets or Sets Stake
        /// </summary>
        [DataMember(Name="stake", EmitDefaultValue=false)]
        public string Stake { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetCommentsReponseComments {\n");
            sb.Append("  CommentText: ").Append(CommentText).Append("\n");
            sb.Append("  ContractId: ").Append(ContractId).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  HideStake: ").Append(HideStake).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LegacyCommentId: ").Append(LegacyCommentId).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  MarketId: ").Append(MarketId).Append("\n");
            sb.Append("  MemberId: ").Append(MemberId).Append("\n");
            sb.Append("  Mentions: ").Append(Mentions).Append("\n");
            sb.Append("  NumComments: ").Append(NumComments).Append("\n");
            sb.Append("  Odds: ").Append(Odds).Append("\n");
            sb.Append("  ParentCommentId: ").Append(ParentCommentId).Append("\n");
            sb.Append("  Reactions: ").Append(Reactions).Append("\n");
            sb.Append("  Stake: ").Append(Stake).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetCommentsReponseComments);
        }

        /// <summary>
        /// Returns true if GetCommentsReponseComments instances are equal
        /// </summary>
        /// <param name="input">Instance of GetCommentsReponseComments to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetCommentsReponseComments input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CommentText == input.CommentText ||
                    (this.CommentText != null &&
                    this.CommentText.Equals(input.CommentText))
                ) && 
                (
                    this.ContractId == input.ContractId ||
                    (this.ContractId != null &&
                    this.ContractId.Equals(input.ContractId))
                ) && 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.EventId == input.EventId ||
                    (this.EventId != null &&
                    this.EventId.Equals(input.EventId))
                ) && 
                (
                    this.HideStake == input.HideStake ||
                    (this.HideStake != null &&
                    this.HideStake.Equals(input.HideStake))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.LegacyCommentId == input.LegacyCommentId ||
                    (this.LegacyCommentId != null &&
                    this.LegacyCommentId.Equals(input.LegacyCommentId))
                ) && 
                (
                    this.Link == input.Link ||
                    (this.Link != null &&
                    this.Link.Equals(input.Link))
                ) && 
                (
                    this.MarketId == input.MarketId ||
                    (this.MarketId != null &&
                    this.MarketId.Equals(input.MarketId))
                ) && 
                (
                    this.MemberId == input.MemberId ||
                    (this.MemberId != null &&
                    this.MemberId.Equals(input.MemberId))
                ) && 
                (
                    this.Mentions == input.Mentions ||
                    this.Mentions != null &&
                    input.Mentions != null &&
                    this.Mentions.SequenceEqual(input.Mentions)
                ) && 
                (
                    this.NumComments == input.NumComments ||
                    (this.NumComments != null &&
                    this.NumComments.Equals(input.NumComments))
                ) && 
                (
                    this.Odds == input.Odds ||
                    (this.Odds != null &&
                    this.Odds.Equals(input.Odds))
                ) && 
                (
                    this.ParentCommentId == input.ParentCommentId ||
                    (this.ParentCommentId != null &&
                    this.ParentCommentId.Equals(input.ParentCommentId))
                ) && 
                (
                    this.Reactions == input.Reactions ||
                    (this.Reactions != null &&
                    this.Reactions.Equals(input.Reactions))
                ) && 
                (
                    this.Stake == input.Stake ||
                    (this.Stake != null &&
                    this.Stake.Equals(input.Stake))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CommentText != null)
                    hashCode = hashCode * 59 + this.CommentText.GetHashCode();
                if (this.ContractId != null)
                    hashCode = hashCode * 59 + this.ContractId.GetHashCode();
                if (this.Created != null)
                    hashCode = hashCode * 59 + this.Created.GetHashCode();
                if (this.EventId != null)
                    hashCode = hashCode * 59 + this.EventId.GetHashCode();
                if (this.HideStake != null)
                    hashCode = hashCode * 59 + this.HideStake.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.LegacyCommentId != null)
                    hashCode = hashCode * 59 + this.LegacyCommentId.GetHashCode();
                if (this.Link != null)
                    hashCode = hashCode * 59 + this.Link.GetHashCode();
                if (this.MarketId != null)
                    hashCode = hashCode * 59 + this.MarketId.GetHashCode();
                if (this.MemberId != null)
                    hashCode = hashCode * 59 + this.MemberId.GetHashCode();
                if (this.Mentions != null)
                    hashCode = hashCode * 59 + this.Mentions.GetHashCode();
                if (this.NumComments != null)
                    hashCode = hashCode * 59 + this.NumComments.GetHashCode();
                if (this.Odds != null)
                    hashCode = hashCode * 59 + this.Odds.GetHashCode();
                if (this.ParentCommentId != null)
                    hashCode = hashCode * 59 + this.ParentCommentId.GetHashCode();
                if (this.Reactions != null)
                    hashCode = hashCode * 59 + this.Reactions.GetHashCode();
                if (this.Stake != null)
                    hashCode = hashCode * 59 + this.Stake.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
